// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "glmSTARMA_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dglmstarma_cpp
Rcpp::List dglmstarma_cpp(const arma::mat& ts, const Rcpp::List& mean_model, const Rcpp::List& dispersion_model, const Rcpp::List& mean_family, const Rcpp::List& dispersion_family, const Rcpp::List& wlist, const Rcpp::List& mean_covariates, const Rcpp::List& dispersion_covariates, const Rcpp::CharacterVector& pseudo_observations, const Rcpp::Nullable<Rcpp::List> wlist_past_mean, const Rcpp::Nullable<Rcpp::List> wlist_covariates, const Rcpp::Nullable<Rcpp::List> wlist_ar_dispersion, const Rcpp::Nullable<Rcpp::List> wlist_past_mean_dispersion, const Rcpp::Nullable<Rcpp::List> wlist_covariates_dispersion, const Rcpp::List& control);
RcppExport SEXP _glmSTARMA_dglmstarma_cpp(SEXP tsSEXP, SEXP mean_modelSEXP, SEXP dispersion_modelSEXP, SEXP mean_familySEXP, SEXP dispersion_familySEXP, SEXP wlistSEXP, SEXP mean_covariatesSEXP, SEXP dispersion_covariatesSEXP, SEXP pseudo_observationsSEXP, SEXP wlist_past_meanSEXP, SEXP wlist_covariatesSEXP, SEXP wlist_ar_dispersionSEXP, SEXP wlist_past_mean_dispersionSEXP, SEXP wlist_covariates_dispersionSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mean_model(mean_modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dispersion_model(dispersion_modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mean_family(mean_familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dispersion_family(dispersion_familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist(wlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mean_covariates(mean_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dispersion_covariates(dispersion_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type pseudo_observations(pseudo_observationsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_past_mean(wlist_past_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_covariates(wlist_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_ar_dispersion(wlist_ar_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_past_mean_dispersion(wlist_past_mean_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_covariates_dispersion(wlist_covariates_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(dglmstarma_cpp(ts, mean_model, dispersion_model, mean_family, dispersion_family, wlist, mean_covariates, dispersion_covariates, pseudo_observations, wlist_past_mean, wlist_covariates, wlist_ar_dispersion, wlist_past_mean_dispersion, wlist_covariates_dispersion, control));
    return rcpp_result_gen;
END_RCPP
}
// glmstarma_cpp
Rcpp::List glmstarma_cpp(const arma::mat& ts, const Rcpp::List& covariate_list, const Rcpp::List& model, const Rcpp::List& wlist_ar, const Rcpp::Nullable<Rcpp::List> wlist_ma, const Rcpp::Nullable<Rcpp::List> wlist_covariates, const Rcpp::List& family, const Rcpp::List& control);
RcppExport SEXP _glmSTARMA_glmstarma_cpp(SEXP tsSEXP, SEXP covariate_listSEXP, SEXP modelSEXP, SEXP wlist_arSEXP, SEXP wlist_maSEXP, SEXP wlist_covariatesSEXP, SEXP familySEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type covariate_list(covariate_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist_ar(wlist_arSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_ma(wlist_maSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_covariates(wlist_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(glmstarma_cpp(ts, covariate_list, model, wlist_ar, wlist_ma, wlist_covariates, family, control));
    return rcpp_result_gen;
END_RCPP
}
// glmstarma_predict
arma::mat glmstarma_predict(const unsigned int& n_ahead, const std::string& pred_type, const arma::mat& ts, const Rcpp::List& covariate_list, const Rcpp::List& model, const Rcpp::List& wlist_ar, const Rcpp::Nullable<Rcpp::List> wlist_ma, const Rcpp::Nullable<Rcpp::List> wlist_covariates, const Rcpp::List& family, const Rcpp::Nullable<Rcpp::List>& new_covariates, const Rcpp::Nullable<arma::mat>& new_obs, const arma::mat& fitted_values, const Rcpp::List& control, const Rcpp::List& parameter_est, Rcpp::Nullable<Rcpp::S4> copula_obj);
RcppExport SEXP _glmSTARMA_glmstarma_predict(SEXP n_aheadSEXP, SEXP pred_typeSEXP, SEXP tsSEXP, SEXP covariate_listSEXP, SEXP modelSEXP, SEXP wlist_arSEXP, SEXP wlist_maSEXP, SEXP wlist_covariatesSEXP, SEXP familySEXP, SEXP new_covariatesSEXP, SEXP new_obsSEXP, SEXP fitted_valuesSEXP, SEXP controlSEXP, SEXP parameter_estSEXP, SEXP copula_objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const unsigned int& >::type n_ahead(n_aheadSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type pred_type(pred_typeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type covariate_list(covariate_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist_ar(wlist_arSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_ma(wlist_maSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_covariates(wlist_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type new_covariates(new_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<arma::mat>& >::type new_obs(new_obsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type fitted_values(fitted_valuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parameter_est(parameter_estSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::S4> >::type copula_obj(copula_objSEXP);
    rcpp_result_gen = Rcpp::wrap(glmstarma_predict(n_ahead, pred_type, ts, covariate_list, model, wlist_ar, wlist_ma, wlist_covariates, family, new_covariates, new_obs, fitted_values, control, parameter_est, copula_obj));
    return rcpp_result_gen;
END_RCPP
}
// dglmstarma_predict
Rcpp::List dglmstarma_predict(const unsigned int& n_ahead, const std::string& pred_type_mean, const std::string& pred_type_dispersion, const arma::mat& ts, const Rcpp::List& mean_model, const Rcpp::List& dispersion_model, const std::string& pseudo_obs_type, const Rcpp::List& mean_family, const Rcpp::List& dispersion_family, const Rcpp::List& wlist, const Rcpp::List& mean_covariates, const Rcpp::List& dispersion_covariates, const arma::mat& pseudo_observations, const Rcpp::Nullable<Rcpp::List> wlist_past_mean, const Rcpp::Nullable<Rcpp::List> wlist_covariates, const Rcpp::Nullable<Rcpp::List> wlist_ar_dispersion, const Rcpp::Nullable<Rcpp::List> wlist_past_mean_dispersion, const Rcpp::Nullable<Rcpp::List> wlist_covariates_dispersion, const Rcpp::List& parameter_est_mean, const Rcpp::List& parameter_est_dispersion, const Rcpp::Nullable<Rcpp::List>& covariate_list_mean_new, const Rcpp::Nullable<Rcpp::List>& covariate_list_dispersion_new, const Rcpp::Nullable<arma::mat> new_obs_mean, const arma::mat& fitted_values_mean, const arma::mat& fitted_values_dispersion, const Rcpp::List& control, const Rcpp::Nullable<Rcpp::S4> copula_obj_mean);
RcppExport SEXP _glmSTARMA_dglmstarma_predict(SEXP n_aheadSEXP, SEXP pred_type_meanSEXP, SEXP pred_type_dispersionSEXP, SEXP tsSEXP, SEXP mean_modelSEXP, SEXP dispersion_modelSEXP, SEXP pseudo_obs_typeSEXP, SEXP mean_familySEXP, SEXP dispersion_familySEXP, SEXP wlistSEXP, SEXP mean_covariatesSEXP, SEXP dispersion_covariatesSEXP, SEXP pseudo_observationsSEXP, SEXP wlist_past_meanSEXP, SEXP wlist_covariatesSEXP, SEXP wlist_ar_dispersionSEXP, SEXP wlist_past_mean_dispersionSEXP, SEXP wlist_covariates_dispersionSEXP, SEXP parameter_est_meanSEXP, SEXP parameter_est_dispersionSEXP, SEXP covariate_list_mean_newSEXP, SEXP covariate_list_dispersion_newSEXP, SEXP new_obs_meanSEXP, SEXP fitted_values_meanSEXP, SEXP fitted_values_dispersionSEXP, SEXP controlSEXP, SEXP copula_obj_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const unsigned int& >::type n_ahead(n_aheadSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type pred_type_mean(pred_type_meanSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type pred_type_dispersion(pred_type_dispersionSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mean_model(mean_modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dispersion_model(dispersion_modelSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type pseudo_obs_type(pseudo_obs_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mean_family(mean_familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dispersion_family(dispersion_familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist(wlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mean_covariates(mean_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dispersion_covariates(dispersion_covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pseudo_observations(pseudo_observationsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_past_mean(wlist_past_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_covariates(wlist_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_ar_dispersion(wlist_ar_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_past_mean_dispersion(wlist_past_mean_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_covariates_dispersion(wlist_covariates_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parameter_est_mean(parameter_est_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parameter_est_dispersion(parameter_est_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type covariate_list_mean_new(covariate_list_mean_newSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type covariate_list_dispersion_new(covariate_list_dispersion_newSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<arma::mat> >::type new_obs_mean(new_obs_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type fitted_values_mean(fitted_values_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type fitted_values_dispersion(fitted_values_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::S4> >::type copula_obj_mean(copula_obj_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(dglmstarma_predict(n_ahead, pred_type_mean, pred_type_dispersion, ts, mean_model, dispersion_model, pseudo_obs_type, mean_family, dispersion_family, wlist, mean_covariates, dispersion_covariates, pseudo_observations, wlist_past_mean, wlist_covariates, wlist_ar_dispersion, wlist_past_mean_dispersion, wlist_covariates_dispersion, parameter_est_mean, parameter_est_dispersion, covariate_list_mean_new, covariate_list_dispersion_new, new_obs_mean, fitted_values_mean, fitted_values_dispersion, control, copula_obj_mean));
    return rcpp_result_gen;
END_RCPP
}
// glmstarma_sim_cpp
Rcpp::List glmstarma_sim_cpp(const Rcpp::IntegerVector& n_obs_in_time, const Rcpp::List& parameters, const Rcpp::List& model, const Rcpp::List& wlist_ar, const Rcpp::Nullable<Rcpp::List> wlist_ma, const Rcpp::List& family, const Rcpp::List& covariates, const Rcpp::Nullable<Rcpp::List> wlist_covariates, const Rcpp::Nullable<Rcpp::S4> copula_obj, const Rcpp::IntegerVector& n_start, const Rcpp::List& control);
RcppExport SEXP _glmSTARMA_glmstarma_sim_cpp(SEXP n_obs_in_timeSEXP, SEXP parametersSEXP, SEXP modelSEXP, SEXP wlist_arSEXP, SEXP wlist_maSEXP, SEXP familySEXP, SEXP covariatesSEXP, SEXP wlist_covariatesSEXP, SEXP copula_objSEXP, SEXP n_startSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type n_obs_in_time(n_obs_in_timeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist_ar(wlist_arSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_ma(wlist_maSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_covariates(wlist_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::S4> >::type copula_obj(copula_objSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type n_start(n_startSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(glmstarma_sim_cpp(n_obs_in_time, parameters, model, wlist_ar, wlist_ma, family, covariates, wlist_covariates, copula_obj, n_start, control));
    return rcpp_result_gen;
END_RCPP
}
// dglmstarma_sim_cpp
Rcpp::List dglmstarma_sim_cpp(const unsigned int& n_obs_in_time, const Rcpp::List& parameters_mean, const Rcpp::List& parameters_dispersion, const Rcpp::List& mean_family, const Rcpp::List& dispersion_family, const Rcpp::List& mean_model, const Rcpp::List& dispersion_model, const std::string& pseudo_observations_type, const Rcpp::List& wlist, const Rcpp::List& mean_covariates, const Rcpp::List& dispersion_covariates, const Rcpp::Nullable<Rcpp::List> wlist_past_mean, const Rcpp::Nullable<Rcpp::List> wlist_covariates, const Rcpp::Nullable<Rcpp::List> wlist_ar_dispersion, const Rcpp::Nullable<Rcpp::List> wlist_past_mean_dispersion, const Rcpp::Nullable<Rcpp::List> wlist_covariates_dispersion, const Rcpp::List& control, const Rcpp::Nullable<Rcpp::S4> copula_obj_mean, const unsigned int& n_start);
RcppExport SEXP _glmSTARMA_dglmstarma_sim_cpp(SEXP n_obs_in_timeSEXP, SEXP parameters_meanSEXP, SEXP parameters_dispersionSEXP, SEXP mean_familySEXP, SEXP dispersion_familySEXP, SEXP mean_modelSEXP, SEXP dispersion_modelSEXP, SEXP pseudo_observations_typeSEXP, SEXP wlistSEXP, SEXP mean_covariatesSEXP, SEXP dispersion_covariatesSEXP, SEXP wlist_past_meanSEXP, SEXP wlist_covariatesSEXP, SEXP wlist_ar_dispersionSEXP, SEXP wlist_past_mean_dispersionSEXP, SEXP wlist_covariates_dispersionSEXP, SEXP controlSEXP, SEXP copula_obj_meanSEXP, SEXP n_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const unsigned int& >::type n_obs_in_time(n_obs_in_timeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parameters_mean(parameters_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parameters_dispersion(parameters_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mean_family(mean_familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dispersion_family(dispersion_familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mean_model(mean_modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dispersion_model(dispersion_modelSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type pseudo_observations_type(pseudo_observations_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist(wlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mean_covariates(mean_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dispersion_covariates(dispersion_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_past_mean(wlist_past_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_covariates(wlist_covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_ar_dispersion(wlist_ar_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_past_mean_dispersion(wlist_past_mean_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List> >::type wlist_covariates_dispersion(wlist_covariates_dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::S4> >::type copula_obj_mean(copula_obj_meanSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type n_start(n_startSEXP);
    rcpp_result_gen = Rcpp::wrap(dglmstarma_sim_cpp(n_obs_in_time, parameters_mean, parameters_dispersion, mean_family, dispersion_family, mean_model, dispersion_model, pseudo_observations_type, wlist, mean_covariates, dispersion_covariates, wlist_past_mean, wlist_covariates, wlist_ar_dispersion, wlist_past_mean_dispersion, wlist_covariates_dispersion, control, copula_obj_mean, n_start));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glmSTARMA_dglmstarma_cpp", (DL_FUNC) &_glmSTARMA_dglmstarma_cpp, 15},
    {"_glmSTARMA_glmstarma_cpp", (DL_FUNC) &_glmSTARMA_glmstarma_cpp, 8},
    {"_glmSTARMA_glmstarma_predict", (DL_FUNC) &_glmSTARMA_glmstarma_predict, 15},
    {"_glmSTARMA_dglmstarma_predict", (DL_FUNC) &_glmSTARMA_dglmstarma_predict, 27},
    {"_glmSTARMA_glmstarma_sim_cpp", (DL_FUNC) &_glmSTARMA_glmstarma_sim_cpp, 11},
    {"_glmSTARMA_dglmstarma_sim_cpp", (DL_FUNC) &_glmSTARMA_dglmstarma_sim_cpp, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_glmSTARMA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
