# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dglmstarma_cpp <- function(ts, mean_model, dispersion_model, mean_family, dispersion_family, wlist, mean_covariates, dispersion_covariates, pseudo_observations, wlist_past_mean, wlist_covariates, wlist_ar_dispersion, wlist_past_mean_dispersion, wlist_covariates_dispersion, control) {
    .Call(`_glmSTARMA_dglmstarma_cpp`, ts, mean_model, dispersion_model, mean_family, dispersion_family, wlist, mean_covariates, dispersion_covariates, pseudo_observations, wlist_past_mean, wlist_covariates, wlist_ar_dispersion, wlist_past_mean_dispersion, wlist_covariates_dispersion, control)
}

glmstarma_cpp <- function(ts, covariate_list, model, wlist_ar, wlist_ma, wlist_covariates, family, control) {
    .Call(`_glmSTARMA_glmstarma_cpp`, ts, covariate_list, model, wlist_ar, wlist_ma, wlist_covariates, family, control)
}

glmstarma_predict <- function(n_ahead, pred_type, ts, covariate_list, model, wlist_ar, wlist_ma, wlist_covariates, family, new_covariates, new_obs, fitted_values, control, parameter_est, copula_obj) {
    .Call(`_glmSTARMA_glmstarma_predict`, n_ahead, pred_type, ts, covariate_list, model, wlist_ar, wlist_ma, wlist_covariates, family, new_covariates, new_obs, fitted_values, control, parameter_est, copula_obj)
}

dglmstarma_predict <- function(n_ahead, pred_type_mean, pred_type_dispersion, ts, mean_model, dispersion_model, pseudo_obs_type, mean_family, dispersion_family, wlist, mean_covariates, dispersion_covariates, pseudo_observations, wlist_past_mean, wlist_covariates, wlist_ar_dispersion, wlist_past_mean_dispersion, wlist_covariates_dispersion, parameter_est_mean, parameter_est_dispersion, covariate_list_mean_new, covariate_list_dispersion_new, new_obs_mean, fitted_values_mean, fitted_values_dispersion, control, copula_obj_mean) {
    .Call(`_glmSTARMA_dglmstarma_predict`, n_ahead, pred_type_mean, pred_type_dispersion, ts, mean_model, dispersion_model, pseudo_obs_type, mean_family, dispersion_family, wlist, mean_covariates, dispersion_covariates, pseudo_observations, wlist_past_mean, wlist_covariates, wlist_ar_dispersion, wlist_past_mean_dispersion, wlist_covariates_dispersion, parameter_est_mean, parameter_est_dispersion, covariate_list_mean_new, covariate_list_dispersion_new, new_obs_mean, fitted_values_mean, fitted_values_dispersion, control, copula_obj_mean)
}

glmstarma_sim_cpp <- function(n_obs_in_time, parameters, model, wlist_ar, wlist_ma, family, covariates, wlist_covariates, copula_obj, n_start, control) {
    .Call(`_glmSTARMA_glmstarma_sim_cpp`, n_obs_in_time, parameters, model, wlist_ar, wlist_ma, family, covariates, wlist_covariates, copula_obj, n_start, control)
}

dglmstarma_sim_cpp <- function(n_obs_in_time, parameters_mean, parameters_dispersion, mean_family, dispersion_family, mean_model, dispersion_model, pseudo_observations_type, wlist, mean_covariates, dispersion_covariates, wlist_past_mean, wlist_covariates, wlist_ar_dispersion, wlist_past_mean_dispersion, wlist_covariates_dispersion, control, copula_obj_mean, n_start) {
    .Call(`_glmSTARMA_dglmstarma_sim_cpp`, n_obs_in_time, parameters_mean, parameters_dispersion, mean_family, dispersion_family, mean_model, dispersion_model, pseudo_observations_type, wlist, mean_covariates, dispersion_covariates, wlist_past_mean, wlist_covariates, wlist_ar_dispersion, wlist_past_mean_dispersion, wlist_covariates_dispersion, control, copula_obj_mean, n_start)
}

